/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carteloto;
import java.awt.*;
import javax.swing.*;
/**
 *
 * @author nadine
 */
public class JeuLoto extends javax.swing.JFrame {

    private Color tabCouleur[]= {Color.red, Color.blue,Color.cyan, Color.green};
    private Color coul;
    private CarteLoto c;
    private int i;
    
    public JeuLoto() {
        initComponents();
        c=new CarteLoto(5, 5);
        this.coul=Color.green;
        afficheValeurs();
        i=0;
    }

        
     public void afficheValeurs()
     { int nbCol=c.getNbColonnes();
       for (int ind= 0; ind< nbCol*c.getNbLignes(); ind++)
        {  JButton jb = (JButton) PanCarte.getComponent(ind);
            int i= ind/nbCol;
            int j= ind - i*nbCol;
            if (c.getCase(i, j)!=0) jb.setText(""+c.getCase(i, j));
            else jb.setText("");
        }
    }
     
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        PanTiitre = new javax.swing.JPanel();
        LTitre = new javax.swing.JLabel();
        PanInfo = new javax.swing.JPanel();
        BInfos = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Edition = new javax.swing.JTextArea();
        PanCarte = new javax.swing.JPanel();
        Bouton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        PanMessage = new javax.swing.JPanel();
        LMessage = new javax.swing.JLabel();
        NomJoueur = new javax.swing.JTextField();
        PanActions = new javax.swing.JPanel();
        BCouleur = new javax.swing.JButton();
        BTirage = new javax.swing.JButton();

        jButton3.setBackground(java.awt.Color.green);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LTitre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LTitre.setForeground(java.awt.Color.red);
        LTitre.setText("Carte de Loto");
        PanTiitre.add(LTitre);

        getContentPane().add(PanTiitre, java.awt.BorderLayout.NORTH);

        PanInfo.setMinimumSize(new java.awt.Dimension(50, 46));
        PanInfo.setLayout(new java.awt.GridLayout(2, 1));

        BInfos.setBackground(new java.awt.Color(255, 0, 51));
        BInfos.setText("Informations");
        BInfos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BInfosActionPerformed(evt);
            }
        });
        PanInfo.add(BInfos);

        jScrollPane2.setPreferredSize(new java.awt.Dimension(96, 96));

        Edition.setBackground(new java.awt.Color(240, 240, 240));
        Edition.setColumns(20);
        Edition.setLineWrap(true);
        Edition.setRows(5);
        jScrollPane2.setViewportView(Edition);

        PanInfo.add(jScrollPane2);

        getContentPane().add(PanInfo, java.awt.BorderLayout.EAST);

        PanCarte.setLayout(new java.awt.GridLayout(3, 5));

        Bouton1.setBackground(java.awt.Color.green);
        PanCarte.add(Bouton1);

        jButton2.setBackground(java.awt.Color.green);
        PanCarte.add(jButton2);

        jButton4.setBackground(java.awt.Color.green);
        PanCarte.add(jButton4);

        jButton5.setBackground(java.awt.Color.green);
        PanCarte.add(jButton5);

        jButton6.setBackground(java.awt.Color.green);
        PanCarte.add(jButton6);

        jButton7.setBackground(java.awt.Color.green);
        PanCarte.add(jButton7);

        jButton8.setBackground(java.awt.Color.green);
        PanCarte.add(jButton8);

        jButton9.setBackground(java.awt.Color.green);
        PanCarte.add(jButton9);

        jButton10.setBackground(java.awt.Color.green);
        PanCarte.add(jButton10);

        jButton11.setBackground(java.awt.Color.green);
        PanCarte.add(jButton11);

        jButton12.setBackground(java.awt.Color.green);
        PanCarte.add(jButton12);

        jButton13.setBackground(java.awt.Color.green);
        PanCarte.add(jButton13);

        jButton14.setBackground(java.awt.Color.green);
        PanCarte.add(jButton14);

        jButton15.setBackground(java.awt.Color.green);
        PanCarte.add(jButton15);

        getContentPane().add(PanCarte, java.awt.BorderLayout.CENTER);

        LMessage.setText("Nom Joueur ");
        PanMessage.add(LMessage);

        NomJoueur.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        NomJoueur.setText("joueur");
        PanMessage.add(NomJoueur);

        getContentPane().add(PanMessage, java.awt.BorderLayout.SOUTH);

        PanActions.setLayout(new java.awt.GridLayout(4, 1));

        BCouleur.setText("Changer Couleur");
        BCouleur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCouleurActionPerformed(evt);
            }
        });
        PanActions.add(BCouleur);

        BTirage.setText("Changer Carte");
        BTirage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTirageActionPerformed(evt);
            }
        });
        PanActions.add(BTirage);

        getContentPane().add(PanActions, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTirageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTirageActionPerformed
        // TODO add your handling code here:
        if (i==0)
        {    c.initAutreCarte(); i=1;}
        else
        { c.initMaCarte(); i=0;}
        afficheValeurs();
                
    }//GEN-LAST:event_BTirageActionPerformed

    private void BCouleurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCouleurActionPerformed
        int ic;
        int nbCol=c.getNbColonnes();
        do{ ic = (int) (Math.random()*tabCouleur.length);
        } while (this.coul.equals(tabCouleur[ic]));
        this.coul= tabCouleur[ic];
        for (int ind= 0; ind< c.getNbLignes()*nbCol; ind++)
        {  JButton jb = (JButton) PanCarte.getComponent(ind);
           jb.setBackground(tabCouleur[ic]);
        }
        
    }//GEN-LAST:event_BCouleurActionPerformed

    private void BInfosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BInfosActionPerformed
        // TODO add your handling code here:
        String nom=NomJoueur.getText();
        Edition.setText("Nom du joueur : "+nom + "\n");
        Edition.append("\n\nNuméros :\n");
        Edition.append(c.toString());
        Edition.append("\n\nCouleur : " + coul.toString() );
        
        
        
    }//GEN-LAST:event_BInfosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JeuLoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JeuLoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JeuLoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JeuLoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JeuLoto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCouleur;
    private javax.swing.JButton BInfos;
    private javax.swing.JButton BTirage;
    private javax.swing.JButton Bouton1;
    private javax.swing.JTextArea Edition;
    private javax.swing.JLabel LMessage;
    private javax.swing.JLabel LTitre;
    private javax.swing.JTextField NomJoueur;
    private javax.swing.JPanel PanActions;
    private javax.swing.JPanel PanCarte;
    private javax.swing.JPanel PanInfo;
    private javax.swing.JPanel PanMessage;
    private javax.swing.JPanel PanTiitre;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
